name: linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install CVMFS
      run: |
        # Get CVMFS working
        wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
        sudo dpkg -i cvmfs-release-latest_all.deb
        sudo apt-get update
        sudo apt-get install cvmfs cvmfs-config-default

        sudo mkdir -p /etc/cvmfs

        cat > default.local <<EOF
        CVMFS_QUOTA_LIMIT='32140'
        CVMFS_HTTP_PROXY=DIRECT
        CVMFS_CACHE_BASE='/var/lib/cvmfs'
        CVMFS_FORCE_SIGNING='yes'
        CVMFS_REPOSITORIES='clicdp.cern.ch,sft.cern.ch,geant4.cern.ch,sw.hsf.org,sw-nightlies.hsf.org'
        CVMFS_SEND_INFO_HEADER=no
        EOF

        sudo mv default.local /etc/cvmfs/default.local
        sudo cvmfs_config setup

        ls /cvmfs/sft.cern.ch
        ls /cvmfs/geant4.cern.ch
        ls /cvmfs/clicdp.cern.ch
        ls /cvmfs/sw.hsf.org

        sudo cvmfs_config probe
        sudo cvmfs_config status

    - name: Start containers
      run: |
        docker run \
            -it --name k4MarlinWrapper_CI \
            -v ${{ github.workspace }}:/k4MarlinWrapper \
            -v /cvmfs/sft.cern.ch:/cvmfs/sft.cern.ch \
            -v /cvmfs/clicdp.cern.ch:/cvmfs/clicdp.cern.ch \
            -v /cvmfs/geant4.cern.ch:/cvmfs/geant4.cern.ch:Z \
            -v /cvmfs/sw.hsf.org:/cvmfs/sw.hsf.org: \
            -v /cvmfs/sw-nightlies.hsf.org:/cvmfs/sw-nightlies.hsf.org: \
            -d clicdp/cc7-lcg96b /bin/bash
    - name: Compile k4MarlinWrapper and run test
      run: |
        docker exec k4MarlinWrapper_CI /bin/bash -c "./k4MarlinWrapper/.github/scripts/k4MarlinWrapper_build_and_test.sh"
